### ISSUE TITLE
Requirements and ideal benchmarks for an MVP implementation

### ISSUE THREAD

**Issue by vaikas** [knative-sandbox/eventing-rabbitmq#239]
### Setup
Generate 100 events/second into a Broker A in Namespace A for 10 seconds
Each event should have a unique id
Trigger A1 (no filters) targeting Broker A
	-> Service A1(with a 2 second sleep before ACK and containerConcurrency=10)
Trigger A2 (filters 50% of events) targeting Broker A
	-> Service A2 (same configuration)

Broker B in Namespace B
Trigger B (no filters) targeting Broker B
         -> Service B

## Expectation from Developer perspective https://github.com/knative-sandbox/eventing-rabbitmq/issues/412
- [ ] all events are processed within 2 minutes
- [ ] Service A1 receives 1000 events with the expected unique ids
- [ ] Service A2 receives 500 events with the expected unique ids
- [ ] Service B receives 0 events

## Expectation from Operator perspective
- [ ] Installation instructions utilizing the 2 upstream operators and their dependencies (cert-manager)  are documented #413 
- [ ] Upgrade instructions are documented #450
- [ ] Observe traces - [reference](https://knative.dev/blog/2021/08/20/distributed-tracing-with-knative-opentelemetry-and-jaeger/) #414 
- [ ] Observe metrics - [reference](https://knative.dev/docs/admin/collecting-metrics/eventing-metrics/metrics/) #415

## Resiliency (Nice to have)
- [ ] Kill pods that aren't event sender pod

**Comment by xtreme-sameer-vohra** [comment]
@evankanderson @benmoss 
Updated the description based on our discussion today. Anything to add ?

**Comment by evankanderson** [comment]
Roughly correct, yes.

It would be nice to have a second broker in a different namespace with a trigger matching at least a few events to make sure we don't cross the streams.

Also, each event should have a unique id, and we should check that the IDs line up at the end.

Bonus points for including a pod kill during the test (we might need more than 10s load to execute that).

**Comment by xtreme-sameer-vohra** [comment]
> Roughly correct, yes.
> 
> It would be nice to have a second broker in a different namespace with a trigger matching at least a few events to make sure we don't cross the streams.
> 
> Also, each event should have a unique id, and we should check that the IDs line up at the end.
> 
> Bonus points for including a pod kill during the test (we might need more than 10s load to execute that).

Thanks updated it.
For the bonus points, which pods should be getting killed ?

**Comment by gvmw** [comment]
This is a WIP comment which will likely be moved to a different place, but since this is our starting point, this is easiest for us (+@ikvmw). Discard/change this when that happens.

---

We chose to set up Knative on GKE Autopilot because that was the easiest thing for us. These are our observations and issues:

- The Knative operator installs itself in the `default` namespace. We were expecting `knative-operator` or something similar. For example, the RabbitMQ operator uses `rabbitmq-system`.

**Comment by xtreme-sameer-vohra** [comment]
> This is a WIP comment which will likely be moved to a different place, but since this is our starting point, we (+@ikvmw) are adding our initial context here.
> 
> We chose to set up Knative on GKE Autopilot because that was the easiest thing for us. These are our observations:
> 
> * The install succeeded within a few seconds, which was nice to see - the first step worked as expected
> * The Knative operator (v0.25.0) installs itself in the `default` namespace. We were expecting `knative-operator` or something similar. For example, the RabbitMQ operator uses `rabbitmq-system`.
> * We have installed the knative-serving components but the activator, autoscaler, webhook and net-istio could not be created in GKE Autopilot due to the following error: `   Error creating: admission webhook "policycontrollerv2.common-webhooks.networking.gke.io" denied the request: GKE Policy Controller rejected the request because it violates one or more policies: {"[denied by autogke-node-affinity-selector-limitation]":["Auto GKE disallows use of cluster-autoscaler.kubernetes.io/safe-to-evict=false annotation on workloads"]}.`. We will restart with a plain GKE cluster.

Autopilot has a bunch of limitations which prevents Knative from working on it. Interestingly looks like their limitations have changed slightly in the docs since it was launched a few months ago.
This might be a good topic at the sync but folks generally use vanilla K8s on Public clouds and kind for local dev.

**Comment by gerhard** [comment]
These are all the commands that we run to provision GKE Autopilot, Crossplane & provider-gcp and then setup a dedicated GKE cluster for Knative:

```
mkdir -p /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/.config/kubectl
mkdir -p /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin
/usr/bin/curl --progress-bar --fail --location --output /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/google-cloud-sdk-355.0.0-Darwin-x86_64.tar.gz "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-355.0.0-Darwin-x86_64.tar.gz"
cd /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin && \
tar -xzf google-cloud-sdk-355.0.0-Darwin-x86_64.tar.gz && \
rm -rf google-cloud-sdk-355.0.0-Darwin-x86_64.tar.gz && \
cd google-cloud-sdk && \
./install.sh --quiet --usage-reporting=false
ln -sf /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/google-cloud-sdk/bin/gcloud /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/gcloud-355.0.0-Darwin-x86_64
ln -sf /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/gcloud-355.0.0-Darwin-x86_64 /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/gcloud
( /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/gcloud-355.0.0-Darwin-x86_64 auth list --filter="status:ACTIVE" --format=yaml | grep --silent lre-admin ) \
|| /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/gcloud-355.0.0-Darwin-x86_64 auth activate-service-account --key-file=/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/lre-admin.key.json
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/gcloud-355.0.0-Darwin-x86_64 container clusters describe messaging-streaming-2021-may 1>/dev/null \
|| time /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/gcloud-355.0.0-Darwin-x86_64 container clusters create-auto messaging-streaming-2021-may \
	--release-channel rapid \
	--scopes storage-rw
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/gcloud-355.0.0-Darwin-x86_64 container clusters get-credentials messaging-streaming-2021-may
/usr/bin/curl --progress-bar --fail --location --output /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm-v3.6.3-darwin-amd64.tar.gz "https://get.helm.sh/helm-v3.6.3-darwin-amd64.tar.gz"
mkdir -p /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm-v3.6.3-darwin-amd64 && tar zxf /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm-v3.6.3-darwin-amd64.tar.gz -C /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm-v3.6.3-darwin-amd64
touch /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm-v3.6.3-darwin-amd64/darwin-amd64/helm
chmod +x /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm-v3.6.3-darwin-amd64/darwin-amd64/helm
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm-v3.6.3-darwin-amd64/darwin-amd64/helm version | grep 3.6.3
ln -sf /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm-v3.6.3-darwin-amd64/darwin-amd64/helm /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm
/usr/bin/curl --progress-bar --fail --location --output /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 "https://storage.googleapis.com/kubernetes-release/release/v1.20.10/bin/darwin/amd64/kubectl"
touch /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64
chmod +x /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 version | grep 1.20.10
ln -sf /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl
/usr/bin/curl --progress-bar --fail --location --output /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/envsubst-1.2.0-Darwin-x86_64 "https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-Darwin-x86_64"
touch /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/envsubst-1.2.0-Darwin-x86_64
chmod +x /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/envsubst-1.2.0-Darwin-x86_64
ln -sf /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/envsubst-1.2.0-Darwin-x86_64 /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/envsubst
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm-v3.6.3-darwin-amd64/darwin-amd64/helm repo add crossplane-stable https://charts.crossplane.io/stable
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm-v3.6.3-darwin-amd64/darwin-amd64/helm repo update
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/helm-v3.6.3-darwin-amd64/darwin-amd64/helm upgrade crossplane crossplane-stable/crossplane \
	--install --version v1.4.1 \
	--namespace crossplane-system --create-namespace --wait \

/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 create secret generic gcp-service-account-key \
	--from-file=creds=/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/lre-admin.key.json \
	--namespace crossplane-system \
	--dry-run=client --output=yaml \
| /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 apply --filename -
export NAMESPACE=crossplane-system \
; export CROSSPLANE_PROVIDER_GCP_VERSION=v0.17.1 \
; cat /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/yaml/crossplane/gcp.yml \
| /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/envsubst-1.2.0-Darwin-x86_64 -no-unset -no-empty \
| /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 apply --filename -
printf "\033[1m\033[1;36mWait for GCP Provider to be healthy...\n\033[0m"
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 wait --for=condition=Healthy=true providers/gcp --timeout=2m
export NAMESPACE=crossplane-system \
; export CROSSPLANE_PROVIDER_GCP_VERSION=v0.17.1 \
; cat /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/yaml/crossplane/gcp-config.yml \
| /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/envsubst-1.2.0-Darwin-x86_64 -no-unset -no-empty \
| /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 apply --filename -
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 config current-context > /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/tmp/kubectl-config-current-context
printf "\033[1m\033[1;36mEnsure that we are targeting the correct GKE cluster, the one that manages all other GKE clusters\n\033[0m"
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 config use-context gke_tanzu-rabbitmq_europe-west2_messaging-streaming-2021-may
export NAMESPACE=crossplane-system \
; export GKE_NAME=knative \
; export GKE_REGION=europe-west3 \
; export GKE_VERSION=1.20 \
; export GKE_MACHINE_TYPE=n1-standard-2 \
; cat /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/yaml/crossplane/gke.yml \
| /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/envsubst-1.2.0-Darwin-x86_64 -no-unset -no-empty \
| /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 apply --filename -
printf "\033[1m\033[1;36mWait for GKE knative cluster and nodepool to be ready...\n\033[0m"
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 wait --for=condition=Ready=true nodepool/knative --timeout=5m
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 wait --for=condition=Ready=true gkecluster/knative --timeout=5m
printf "\033[1m\033[1;36mGet GKE knative cluster credentials...\n\033[0m"
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/gcloud-355.0.0-Darwin-x86_64 container clusters get-credentials knative --region europe-west3
printf "\033[1m\033[1;36m⚠️  If you want to target this new GKE cluster, remember to switch the kubectl context ⚠️\n\033[0m"
/Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/bin/kubectl-1.20.10-darwin-amd64 config use-context $(cat /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/tmp/kubectl-config-current-context)
rm -f /Users/gerhard/github.com/rabbitmq/infrastructure/k8s/gke/tmp/kubectl-config-current-context
```

In our case, it is a matter of running `make crossplane crossplane-gke` from within our private infrastructure repository: https://github.com/rabbitmq/infrastructure

These yaml files capture the config for Crossplane provider-gcp & the resulting GKE:

```yaml
# gcp.yml
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: gcp
spec:
  package: crossplane/provider-gcp:${CROSSPLANE_PROVIDER_GCP_VERSION}

# gcp-config.yml
---
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp
spec:
  projectID: tanzu-rabbitmq
  credentials:
    source: Secret
    secretRef:
      namespace: ${NAMESPACE}
      name: gcp-service-account-key
      key: creds

# gke.yml
---
apiVersion: container.gcp.crossplane.io/v1beta1
kind: GKECluster
metadata:
  name: ${GKE_NAME}
spec:
  providerConfigRef:
    name: gcp
  forProvider:
    location: ${GKE_REGION}
    initialClusterVersion: "${GKE_VERSION}"
  writeConnectionSecretToRef:
    name: ${GKE_NAME}-gke
    namespace: ${NAMESPACE}
---
apiVersion: container.gcp.crossplane.io/v1alpha1
kind: NodePool
metadata:
  name: ${GKE_NAME}
spec:
  providerConfigRef:
    name: gcp
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: true
      maxNodeCount: 9
      minNodeCount: 1
    clusterRef:
      name: ${GKE_NAME}
    config:
      diskSizeGb: 100
      diskType: pd-ssd
      imageType: cos_containerd
      labels:
        managed-by: crossplane
      machineType: ${GKE_MACHINE_TYPE}
      oauthScopes:
        - "https://www.googleapis.com/auth/devstorage.read_only"
        - "https://www.googleapis.com/auth/logging.write"
        - "https://www.googleapis.com/auth/monitoring"
        - "https://www.googleapis.com/auth/servicecontrol"
        - "https://www.googleapis.com/auth/service.management.readonly"
        - "https://www.googleapis.com/auth/trace.append"
    initialNodeCount: 1
    locations:
      - ${GKE_REGION}-a
    management:
      autoRepair: true
      autoUpgrade: true
  writeConnectionSecretToRef:
    name: ${GKE_NAME}-gke-nodepool
    namespace: ${NAMESPACE}
```

The simplest thing may be to just share the GKE cluster, and each of us use their own namespace for https://github.com/ikvmw/eventing/tree/main/test/performance and the development pre-requisite: https://github.com/knative/eventing/blob/main/DEVELOPMENT.md

WDYT @gabo1208?

**Comment by gabo1208** [comment]
Sounds good to me, so we would have the same env to start working in those tests 👍🏼

**Comment by gerhard** [comment]
The goal is to keep the context in a single place - this GKE cluster - and make shared progress. If we each create our own namespace for experiments, then we will avoid stepping on each other's feet, and not duplicate the same base resources: knative, rabbitmq-cluster-operator, rabbitmq-topology-operator, cert-manager etc.

**Comment by gvmw** [comment]
We have agreed with @ikvmw to wrap this up via the following steps:
- [ ] contribute a new doc that outlines the steps necessary to perform this benchmark
- [ ] contribute a Makefile & relevant YAML that performs all steps in this doc

**Comment by xtreme-sameer-vohra** [comment]
Thanks @gvmw
Should we move the `Expectation from Operator perspective` into a separate issue, so #445 can close this issue ?

**Comment by gvmw** [comment]
I would rename this issue to `How can I benchmark eventing-rabbitmq?` and update the content to focus on what end-users will be able to achieve after this is delivered.

I would mention GKE as a starting point, because KiND is not a good place to start benchmarking.

I would also mention where we want this to live - I think the repo - and how we expect users to run it. My default go-to is Makefiles that pull dependencies (including `kubectl` & `ko`), and know which commands to run & in which order (a.k.a. dependencies between targets), but maybe you imagine users running this differently. What I care about is anyone being able to run everything with a single command, given that they have pre-requisites set up (make & a KUBECONFIG pointing to a fresh GKE 1.20 cluster), and end with the same end-result. Knowing what numbers we want to use for the benchmark is super useful, so I would keep that.

As for the next step, I think that we should shift focus to **Get Started with Knative Eventing - RabbitMQ**, and then maybe come back to automating benchmarks - manual for now is good enough. That feels like a good direction to start walking towards, but I'm curious how this matches your vision for eventing-rabbitmq @xtreme-sameer-vohra 🙂

**Comment by xtreme-sameer-vohra** [comment]
> I would rename this issue to `How can I benchmark eventing-rabbitmq?` and update the content to focus on what end-users will be able to achieve after this is delivered.

Just realized that https://github.com/knative-sandbox/eventing-rabbitmq/issues/412 covers this. 
This issue was useful to align on requirements, which has happened so it can be closed. Added links to open issues for `Expectation from Operator perspective` section

> 
> I would mention GKE as a starting point, because KiND is not a good place to start benchmarking.

Agreed that we don't want to rely on KiND for getting consistent benchmarking results.
> 
> I would also mention where we want this to live - I think the repo - and how we expect users to run it. My default go-to is Makefiles that pull dependencies (including `kubectl` & `ko`), and know which commands to run & in which order (a.k.a. dependencies between targets), but maybe you imagine users running this differently. What I care about is anyone being able to run everything with a single command, given that they have pre-requisites set up (make & a KUBECONFIG pointing to a fresh GKE 1.20 cluster), and end with the same end-result. Knowing what numbers we want to use for the benchmark is super useful, so I would keep that.

The setup artifacts (scripts, yaml, etc) can live in the repo's test directory, but I'll defer to @benmoss.  Ditto in regards to using `Makefiles` or not. 
Its safe to assume the person running the benchmark knows about kubectl, ko, etc but feel free to simplify if it is low effort.

> 
> As for the next step, I think that we should shift focus to **Get Started with Knative Eventing - RabbitMQ**, and then maybe come back to automating benchmarks - manual for now is good enough. That feels like a good direction to start walking towards, but I'm curious how this matches your vision for eventing-rabbitmq @xtreme-sameer-vohra 🙂

💯 Yes, that makes sense. Automating the benchmarks can be re-visited once the [MVP items](https://github.com/knative-sandbox/eventing-rabbitmq/projects/1#column-13186271) such as `Getting Started` are done.

**Comment by gvmw** [comment]
While https://github.com/knative-sandbox/eventing-rabbitmq/pull/445 contains the YAML that configures the benchmark, and we (+@ikvmw) also intend to have the step-by-step guide in that PR as well, I wanted to start with the WIP guide variant here, and move it across when it's done. Here it goes:

## 1/n. Pre-requisites

- GKE 1.20 with
- kubectl 1.20
- [ko 0.9.3](https://github.com/google/ko/releases/tag/v0.9.3) 
- A git clone of [knative-sandbox/eventing-rabbitmq](https://github.com/knative-sandbox/eventing-rabbitmq) at tag v0.27.0 or higher

We use GKE with **c2-standard-4**  machine type to make benchmarks results consistent. Using a different instance type, or a different cloud provider, is almost certain to yield different results.

## 2/n. Install Knative on GKE

We install a specific version of Knative - [v0.26.0](https://github.com/knative/eventing/releases/tag/v0.26.0) - as this is a point-in-time guide. While we expect subsequent versions to continue working the same way, without the necessary automation to ensure this, we stick to exact versions that we know to work together.

```
kubectl apply --filename https://github.com/knative/serving/releases/download/v0.26.0/serving-crds.yaml
```

> Aside: does this look right to you @benmoss ? https://github.com/knative/serving/releases/download/v0.26.1/serving-crds.yaml . I didn't install v0.26.1 - latest release - because of it.

## TO BE CONTINUED
