### ISSUE TITLE
Validate & Document Trigger's behavior under non-happy conditions

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#592]
**Problem**
Validate and document/reference the default retry behaviour from the Trigger Dispatcher -> Sink and under what circumstances (eg. HTTP codes)

Additionally, document/reference ([DeliverySpec, Requeue](https://github.com/knative-sandbox/eventing-rabbitmq/blob/e4db575945e91966a27894c09927a24014b8fa80/cmd/dispatcher/main.go#L40-L51))  & validate how they impact behavior (eg. redelivery) under the following scenarios;
- [x] Trigger's sink is not available -- #720 
- [x] Trigger's sink responds with a [non 2xx & non-retry status code](https://github.com/knative/specs/blob/main/specs/eventing/data-plane.md#event-acknowledgement-and-delivery-retry) #720 
- [x] Trigger's sink responds with a [retryable status code](https://github.com/knative/specs/blob/main/specs/eventing/data-plane.md#event-acknowledgement-and-delivery-retry) #720
- [x] #671
- [x] Trigger's dispatcher fails without ack'ing message from RabbitMQ -- RabbitMQ will wait for the default 30 minutes for the ACK, the channel closed and outstanding messages requeued. 
- [x] Broker/Trigger have a deadLetterSink configured #720 

See [Event Delivery in Knative Specs](https://github.com/knative/specs/blob/main/specs/eventing/control-plane.md#event-delivery) for expected behavior for some of the defined scenarios.

## Open Questions
- if no delivery spec is configured, does the kn cloud events client retry 3 times automatically ?
- how visibility timeouts (crashed/unresponsive KService) affect ordering due to 10s default hearbeat timeout currently used streadway/amqp@master/connection.go#L133-L136.
- Will RabbitMQ wait for a ACK/NACK forever when a reading client pops a message from the queue, unless the connection between the reading client and RabbitMQ dies ? If so, what are the TCP connection timeouts ? Are those being configured in eventing-rabbitmq ?
- When a message is NACK by the dispatcher, how long does it take for the message to be available back in the RabbitMQ queue to be consumed for delivery ?

#### More Context
[Queue-Despair-Ordering-And-Poison-Messages](https://www.openmymind.net/Queue-Despair-Ordering-And-Poison-Messages/) sheds light on an issue a system can run into. In this case, as a user, you would want to understand system's default behavior under scenarios like poison messages and what configurable knobs are available to change behavior. 

Visibilty - The amount of time RMQ will wait for ACK/NACK from a client for a message

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
- Application Developers

**Exit Criteria**
Documented behaviour in markdown files in the repo

**Time Estimate (optional):**

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by gab-satchi** [comment]
Some answers to the open Q's since a lot of the answers are RabbitMQ related and not controlled by this repo.

1. if no delivery spec is configured, does the kn cloud events client retry 3 times automatically ?
No, there currently isn't a default being used when delivery spec isn't defined. If delivery spec is defined, but retry isn't, we default to [5](https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/pkg/reconciler/trigger/resources/dispatcher.go#L105-L111). Unsure what the original reasoning for that was.

1. how visibility timeouts (crashed/unresponsive KService) affect ordering due to 10s default hearbeat timeout currently used streadway/amqp@master/connection.go#L133-L136.
Ordering will only be affected if the `parallelism` variable is set through the trigger annotation. More in-depth explanation [here](https://github.com/knative-sandbox/eventing-rabbitmq/tree/main/docs/broker#trigger-pre-fetch-count)

1. Will RabbitMQ wait for a ACK/NACK forever when a reading client pops a message from the queue, unless the connection between the reading client and RabbitMQ dies ? If so, what are the TCP connection timeouts ? Are those being configured in eventing-rabbitmq ?
RabbitMQ will wait (by default) 30 minutes for a ACK/NACK before it considers the message lost and requeues. This setting is configurable [on the server](https://www.rabbitmq.com/consumers.html#acknowledgement-timeout).

1. When a message is NACK by the dispatcher, how long does it take for the message to be available back in the RabbitMQ queue to be consumed for delivery ?
We currently do not requeue the message during NACKs. Users can set the retry count in the delivery spec to a finite number. 

Will close this issue once the linked PRs are merged
