### ISSUE TITLE
Redesigning RabbitMQSource API

### ISSUE THREAD

**Issue by gab-satchi** [knative-sandbox/eventing-rabbitmq#765]
**Problem**
There are a few things that stand out with the current RabbitMQSource API:
- When using RabbitMQ Cluster, there's no easy way to simply reference it in RabbitMQSource and have it connect. The user has to edit their `default-user` secret, add the uri and reference the secret in the RabbitMQSource.
- Some options like Exchange type don't work
- There are options exposed through the various resource configs (Exchange, Queue) that don't really add value or are a no-op to the Source's use case (more in context below)

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
System Integrator

**Exit Criteria**
Provided a redesign is warranted, the following needs to be done
Finalize API and then fill out a task list
- [x] Limit the actual use cases for the current Source to avoid broken ones #795 #800 
- [x] Start deprecation notices on the Source Readme #795 
- [ ] Send email to the community communicating the Source API change
- [ ] Finalize the change discussion and definition for the Source 1.0
- [x] Trim all the deprecated Source Spec parameters and implement the new validations #800 
- [x] Use RabbitMQ's Cluster reference in the source #801
- [ ] Update docs and samples
- [ ] Upgrade instructions or conversion webhooks for sources

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
The following is the current spec along with comments highlighting areas for discussion:

``` yaml
apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
spec:
  broker: "rabbitmq:5672/" # RabbitMQBroker uri. Currently used by the adapter deployment, can be simplified into RabbitMQClusterReference
  user: # Only used by the adapter deployment, can be simplified into RabbitMQClusterReference
    secretKeyRef:
      name: rabbitmq-default-user
      key: username
  password: # Only used by the adapter deployment, can be simplified into RabbitMQClusterReference
    secretKeyRef:
      name: rabbitmq-default-user
      key: password
  connectionSecret:
    name: "some-secret"
  channelConfig:
    parallelism: 1
    globalQos: false # The global QoS won't have any effect. The adapter uses a single channel off of a connection. Can just hardcode to false and not expose as an option
  exchangeConfig:
    name: "eventing-rabbitmq-source-exchange"
    type: "fanout" # The type (and following attributes) only matter when it isn't predeclared. It's a 1:1 setup of Exchange and Queue when predeclared is false. No need to have type configurable
    durable: true # Should hardcode to true and not be configurable
    autoDelete: false # Should hardcode to false and not be configurable. If exchange gets deleted, it would likely just get recreated during the next reconcile
  queueConfig:
    name: "eventing-rabbitmq-source-queue"
    routingKey: "some-key" # Routing key (and following attributes) only matter when it isn't predeclared. Routing key not needed in a 1:1 setup of Exchange + Queue
    durable: true # Should hardcode to true and not be configurable
    autoDelete: false # Should hardcode to false and not be configurable.
  predeclared: false
  retry: 5
  backoffPolicy: "linear"
  backoffDelay: "5ms"
  serviceAccountName: "some-account-name"
  vhost: "/"
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: rabbitmq-source-sink
      namespace: source-demo

```

The following is a suggestion for consolidating all the fields required for connecting to a RabbitMQ server into a block in the spec called `RabbitmqClusterReference`. Copied from what's used in the Topology Operator:

``` golang
type RabbitmqClusterReference struct {
	// The name of the RabbitMQ cluster to reference.
	// Have to set either name or connectionSecret, but not both.
	// +kubebuilder:validation:Optional
	Name string `json:"name,omitempty"`
	// The namespace of the RabbitMQ cluster to reference.
	// Defaults to the namespace of the requested resource if omitted.
	// +kubebuilder:validation:Optional
	Namespace string `json:"namespace,omitempty"`
	// Secret contains the http management uri for the RabbitMQ cluster.
	// The Secret must contain the key `uri`, `username` and `password` or operator will error.
	// Have to set either name or connectionSecret, but not both.
	// +kubebuilder:validation:Optional
	ConnectionSecret *corev1.LocalObjectReference `json:"connectionSecret,omitempty"`
}
```

If all of the suggestions from above are applied (TODO: update after discussions), the new RabbitMQ Source spec would be:
``` yaml
apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
spec:
  rabbitmqClusterReference:
    name: "rmqCluster"
    namespace: "default"
  parallelism: 1 # Channel config flattened
  rmqResources:
    exchangeName: "eventing-rabbitmq-source-exchange" # Can also be implied if unset while predeclared is false
    queueName: "eventing-rabbitmq-source-queue" # Can also be implied if unset while predeclared is false
    predeclared: false
  delivery: # introduce deliverySpec similar to Broker/Trigger
    retry: 5
    backoffPolicy: "linear"
    backoffDelay: "5ms"
  serviceAccountName: "some-account-name"
  vhost: "/"
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: rabbitmq-source-sink
      namespace: source-demo
```

If it's a predeclared setup, the spec get a bit simpler where exchangeName can become optional. Following is an example with predeclared non-managed RabbitMQ server:

```yaml
apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
spec:
  rabbitmqClusterReference:
    connectionSecret:
      name: "some-secret-name" # namespace is inferred as it's a localObjectReference
  parallelism: 1 # Channel config flattened
  rmqResources:
    exchangeName: "" # optional. won't get used when predeclared
    queueName: "eventing-rabbitmq-source-queue" # required as the dispatcher will consume from this queue
    predeclared: true
  delivery: # introduce deliverySpec similar to Broker/Trigger  
    retry: 5
    backoffPolicy: "linear"
    backoffDelay: "5ms"
  serviceAccountName: "some-account-name"
  vhost: "/"
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: rabbitmq-source-sink
      namespace: source-demo
```

**Comment by gabo1208** [comment]
Agree with all the observations, I'm just not clear where the connection secret went :p

**Comment by ChunyiLyu** [comment]
@gab-satchi Looks good! Love to see the API getting simplified. The example you listed at the end is for non-predeclared, maybe it's also useful to include a predeclared "true" example manifest?

Regarding how the rabbitmqsource controller and adaptor connect to the RabbitMQ server. I like the idea of using [RabbitmqClusterReference](https://github.com/rabbitmq/messaging-topology-operator/blob/968ca948d78a5d7f551ec65eb5d6ba41b3755a4a/api/v1beta1/rabbitmq_cluster_reference.go#L10-L24) directly. The controller might need to have certain logic such as only specify name or connectionSecret but not both, for example: https://github.com/rabbitmq/messaging-topology-operator/blob/968ca948d78a5d7f551ec65eb5d6ba41b3755a4a/api/v1beta1/rabbitmq_cluster_reference.go#L49-L64

**Comment by gab-satchi** [comment]
Thanks @ChunyiLyu, updated with a predeclared setup. 

We'll also be adding the same validations around RabbitmqClusterReference as the topology-operator

**Comment by gab-satchi** [comment]
@gabo1208 a couple of changes since you self-assigned, I updated the proposed spec a bit to introduce `rmqResources` and `delivery`. We also need to fill out the TODO task list in here which may lead to new issues since this is a fairly large change

**Comment by gabo1208** [comment]
Gab Some changes that I think could be a little differente (I'll update the issue if this get pass):
- Vhost is now not needed, we have the same behavior as the broker when we manage all of this with the cluster reference and connection secret
- Im plannning to leave the `exchangeConfig` and `channelConfig` as separate config blocks in the yaml, instead of using the `rmqResources` cause its easier to add things again there in case we need to than to add lot of different config params into the `rmqResources` block

WDYT @gab-satchi

**Comment by gab-satchi** [comment]
1) RabbitmqClusterReference will give us the cluster URL but I'd think vhost would still be needed if resources are grouped under a vhost
1) Since we're removing the extra options now (with good reason), I don't know if we want to anticipate reintroducing them. We'll be having 3 structs with single fields in them. I think in the future if more configurations were getting introduced and the `rmqResources` gets overloaded, we can introduce another struct and provide a conversion webhook to convert to the new api.

**Comment by gabo1208** [comment]
1. I'm testing the VHost removal now so I'll update here with the results
2. Kk fair enough, but I'll propose that PR #800 goes through and then I'll send a separate PR with the restructuring of the delivery and rmq resources params

**Comment by gabo1208** [comment]
I think this is done cc @gab-satchi
